```{r}
#Set Working Directory so that files save back in folder
setwd('C:/Users/aalvarado55/OneDrive - University of California Merced/00_Alvarado_ESF Junior Specialist/03_Data/03_CO2bie Flux/01_Calibrated_CO2bies/')
```

```{r}

library(dplyr)
flux_data <- XLConnect::readWorksheetFromFile("Summary Flux Values_Origional.xlsx", sheet = "Excluding Stat. Outliers", colTypes=c("Date","Date","numeric"))[-1,c(2,3)] #%>%
flux_data

names(flux_data) <- c("Date", "CO2 efflux (µmol.m-2.s-1)")
flux_data
```

```{r}

library(ggplot2)

graph1 <- ggplot(flux_data, aes(x = Date, y = `CO2 efflux (µmol.m-2.s-1)`)) + 
  geom_boxplot(aes(group = Date))+
  labs(title = expression("ESF CO"[2]*" efflux"),
       x = "Date",
       y = expression("CO"[2]*" efflux ("*µ*mol/m^2*s*")")) +

  theme_bw()

graph1

graph2 <- ggplot(flux_data, aes(x = Date, y = `CO2 efflux (µmol.m-2.s-1)`)) + 
  geom_boxplot(aes(group = Date)) +
  scale_x_datetime(limits = c(as.POSIXct("2022-07-01"), as.POSIXct("2022-11-30")), expand=c(0,0)) +
  labs(title = expression("ESF CO"[2]*" efflux 2022 Field Methods Class"),
       x = "Date",
       y = expression("CO"[2]*" efflux ("*µ*mol/m^2*s*")")) +

   theme_bw()

graph2

ggsave("Boxplot ESF Co2flux_timewithgaps.png", graph1, dpi = 300,units="in", width=8,height=5)
ggsave("Boxplot ESF Co2flux_timewithgaps_2022FieldMethodsCourse.png", graph2, dpi = 300,units="in", width=8,height=5)


```