```{r}

# Libraries --------------------------------------------------------------------
library(dplyr)
library(ggplot2)
library(XLConnect)

```


```{r}
#Set Working Directory so that files save back in folder
setwd('C:/Users/aalvarado55/OneDrive - University of California Merced/00_Alvarado_ESF Junior Specialist/03_Data/03_CO2bie Flux/01_Calibrated_CO2bies/')
```


```{r}
flux_data <- XLConnect::readWorksheetFromFile("Summary Flux Values_Origional.xlsx", sheet = "Excluding Stat. Outliers", colTypes=c("Date","Date","numeric"))[-1,c(2,3)] #%>%
# remame(Date = Col2, 
 #        CO2.efflux = c
flux_data

names(flux_data) <- c("Date", "CO2 efflux (µmol.m-2.s-1)")
flux_data
```
```{r}
subset_flux_data <- subset(flux_data, Date >= as.POSIXct("2022-07-01") & Date <= as.POSIXct("2022-11-30"))
print(subset_flux_data)

flux_data$Date <- as.factor(flux_data$Date)  # Convert Date column to factor

graph1 <- ggplot(flux_data, aes(x = Date, y = `CO2 efflux (µmol.m-2.s-1)`)) + 
  geom_boxplot() +
  scale_x_discrete(labels = function(x) format(as.Date(x), "%Y-%m-%d")) +  # Format x-axis labels
  labs(title = expression("ESF CO"[2]*" efflux"),
       x = "Date",
       y = expression("CO"[2]*" efflux ("*µ*mol/m^2*s*")")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  # Rotate x-axis labels vertically

graph1

ggsave("Boxplot ESF Co2flux.png", graph1, dpi = 300,units="in", width=8,height=5)

```
